version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:sa-east-1:278119224443:task-definition/jwt-validator"
        LoadBalancerInfo:
          ContainerName: "jwt-validator"
          ContainerPort: 8080
